[pytest]
minversion = 7.0
addopts = --cov=src --cov-report term-missing
pythonpath = src
testpaths = tests
env =
    DEBUG=False
    POD_NAME=test-pod
    DRY_RUN=False
    TESTING=False
    TEST_CPR_NUMBER=0102030405
